### ISSUE TITLE
Removal of GuzzleSoapClientDriver

### ISSUE THREAD

**Issue by ghost** [slevomat/eet-client#17]
Default SoapClient does have connection_timeout option and also there is common runtime configuration option default_socket_timeout to set timeout for all socket based streams.

Eventually there could be implemented very simple workaround using cURL instead of using another external library not distributed with PHP by default (see http://stackoverflow.com/a/3500554/2678658 for code example)

Keep things simple :-)

**Comment by janlanger** [comment]
Obě možnosti jsme zvažovali a zavrhli... `default_socket_timeout` je globální nastavení a knihovna by globální nastavení určitě ovlivňovat neměla. Navíc nativní SoapClient se občas umí chovat divně, např. v některých případech nedostupnosti cílové služby vyhodil fatal error místo exception, což se ošetřuje dost těžko. 

Interně používáme na http komunikaci guzzle, tak to byla logická volba. Je to široce používaná otestovaná knihovna s jednoduchým api. 

Což ale nemění nic na tom, že guzzle není povinnost použít, je možné si udělat vlastní implementaci `SoapClientDriver` třeba pomocí curl (a případně poslat PR).

**Comment by ghost** [comment]
Pravda, pokud se jiz pouziva i jinde v kodu, pak neni duvod nevyuzit i zde...
Ok tedy, issue bych s klidnym svedomim zavrel a budu-li citit potrebu, tak bych odjel alternativniho clienta pro ty, kteri guzzle jinak nepouzivaji ;-)
