### ISSUE TITLE
EvidenceResponse::getRawData() nevrací všechna data

### ISSUE THREAD

**Issue by hubipe** [slevomat/eet-client#21]
Narazil jsem na to, že z EvidenceResponse nelze vytáhnout všechna data z odpovědi XML. Raw data například neobsahují texty chyb (pouze atributy XML), nebo varování. Nelze tak nijak z knihovny vyexportovat všechna varování. Celý stdClass se vůbec nějak podivně serializuje:

```
Hlavicka => stdClass #2cfe
  uuid_zpravy => "f11c788c-f67a-41ea-9451-922ca9946a47" (36)
  bkp => "C0E71E70-7426660E-3CDB300F-23264AE2-29C3B485" (44)
  dat_prij => "2017-02-21T17:18:59+01:00" (25)
Potvrzeni => stdClass #d2ba
  fik => "c977ab23-76a0-4cc1-b0c3-6bdb6429815f-ff" (39)
  test => TRUE
Varovani => stdClass #7288
  kod_varov => 1
```

**Comment by janlanger** [comment]
Převod dat z XML dělá nativní php `SoapClient` který se při tom řídí XSD schématem (který je od Finanční správy). Data tedy nejspíš nejsou ve výstupu kvůli tomu jak FS element `Varovani` nadefinovala. Nicméně do XSD bych nerad zasahoval protože je oficiální. 

Myslím ale že text u chyb a varování odpovídá významu kódů v dokumentaci EET (ale souhlas že by bylo víc user-friendly mít text ve výstupu...).

**Comment by hubipe** [comment]
A co možnost udělat si vlastní parser navrácených dat? Pokud bych se mohl dostat k `SoapClient`, mohl bych si vytáhnout poslední odpověď přes `__getLastResponse()`. Bohužel `SoapClient` je zapouzdřen v `Client`.

**Comment by vaclavvanik** [comment]
`__doRequest()` by musel [nastavovat interní atributy](http://php.net/manual/en/soapclient.dorequest.php#111664), aby vám __getLastResponse() fungovalo. Jinak pokud používáte Guzzle, tak přes [handlerStack](http://docs.guzzlephp.org/en/latest/handlers-and-middleware.html) se dostanete k response i request.

**Comment by hubipe** [comment]
OK, v tom případě zavirám. Díky za knihovnu.
