### ISSUE TITLE
Kontrola existence cesty k veřejnému klíči

### ISSUE THREAD

**Issue by jost125** [slevomat/eet-client#23]
Trošku jsem se natrápil, když jsem měl typo v cestě k veřejnému klíči a jediné co jsem dostával bylo, že nemám správně podepsanou zprávu (až jako odpověď od serveru). Nečekal jsem, že implementace přes tu knihovnu na WSE, nekontroluje existenci cesty a silent to podepisuje nějakým nesmyslem.

Možná by bylo fajn přidat kontrolu na existenci klíče. (Tuším že cestu k privátnímu klíči to kontroluje v části kde se počítá PKP).

**Comment by janlanger** [comment]
👍Můžeš poslat PR?

**Comment by jost125** [comment]
Zkusil jsem něco zplodit tady:
https://github.com/slevomat/eet-client/pull/24

Mimochodem, `SlevomatEET\ClientFunctionalityTest::testFunctionality` padá celkem dost náhodně a celkem dost často (stihne vytimeoutovat). Možná by stálo za to tam dát větší timeout.
