### ISSUE TITLE
Extrahování p12

### ISSUE THREAD

**Issue by sonnyCZE** [slevomat/eet-client#25]
Dobrý den,

implementace testovacího prostředí byla opravdu jednoduchá - za to bychom chtěli poděkovat.

Máme ale problém při získání soukromého a veřejného klíče z p12 pro produkční prostředí vygenerováno přes https://ca1.eet.cz/app/createRequest.  Pomocí
`$ openssl pkcs12 -in 1980770601.p12 -nocerts -out private.key`
`$ ssh-keygen -y -f private.key > public.pub`
jsem si získal potřebné soubory, ale při podpisu dostávám error 4 Neplatny podpis SOAP zpravy. Předpokládám, že problém je v postupu extrahování dat z p12. Mohl bych poprosit o postup získání potřebných souborů?

Přepnutí prostředí, zapnutí ověřovacího módu a kontrolu správnosti cest ke klíčům jsem udělal.

**Comment by PavelJurasek** [comment]
Já extrahoval klíče z p12 takto
```$ openssl pkcs12 -in xxx.p12 -out public.pub -clcerts -nokeys```
```$ openssl pkcs12 -in xxx.p12 -out private.key -nocerts```
a zdá se, že funguje.

**Comment by sonnyCZE** [comment]
Děkuji moc. Už dostávám error kód 0, což znamená, že vše funguje.

**Comment by janlanger** [comment]
Díky za připomínku, doplníme do dokumentace
