### ISSUE TITLE
Otázka: Celková tržba

### ISSUE THREAD

**Issue by kironet** [slevomat/eet-client#28]
Dobrý den,

opravdu musím odesílat částku v setinách? Protože, jsem to hledal v etržby dokumentaci, a nikde jsem to nenašel. Ve vzoru je tohle: 

Celková částka tržby         celk_trzba          3264.00

A není napsáno, jestli to je 3200Kč nebo 32,64Kč.... Spíše bych se přiklonil k tomu prvnímu.

**Comment by janlanger** [comment]
To je implementační věc této knihovny. Částky jsou celá čísla abychom se vyhnuli problémům se zaokrouhlováním floatů.

>  Tedy pokud chcete odeslat tržbu 55.5 Kč, vložíte do třídy Receipt hodnotu jako integer 5550.
