### ISSUE TITLE
Neodesílá faktury a vrací špatný PKB

### ISSUE THREAD

**Issue by kironet** [slevomat/eet-client#29]
Dobrý den,

jíž od včerejšího večera(13.6.2017) mi nejde odeslat platbu na EET. Vrací to PKB v takovém formátu: 

> pdZ: uUCJwbkfi:LONh^dGoJQFxIA(!ma`
> N%`'qLg51?uwEG:Xl=[ph
> 
> cm[A6JIZH?~0;/LLt)CơRw8>#G}W~73M
> gpO$&]$
> ~:\
> TPk[.efR?

Zkoušel jsem se včera dostat na portal etržeb, ale bylo tam uvedeno, že system nefunguje a na opravach se pracuje. Teď to vypadá, že etržby fungují, ale faktury se pořád neodesílají na EET. 

Můj kód(poslední úprava před 2 měsíci)

```
        $crypto = new CryptographyService($this->container->get('kernel')->getRootDir() . '/Certificates/private.key', $this->container->get('kernel')->getRootDir() . '/Certificates/public.pub', 'Gz711bk96xi');
        $configuration = new Configuration(
            "$this->dicPoplatnik",
            "$this->cisloProvozovny",
            "$this->cisloPokladny",
            EvidenceEnvironment::get(EvidenceEnvironment::PRODUCTION),
            false
        );
        $client = new Client($crypto, $configuration, new GuzzleSoapClientDriver(new \GuzzleHttp\Client()));

        $receipt = new Receipt(
            true,
            $this->dicKupujici,
            "$this->cisloFaktury",
            $this->datumPlatby,
            ($this->cena * 100)
        );

        try {
            $response = $client->send($receipt);
            return ['fik' => $response->getFik(), 'bkp' => $response->getBkp(), 'pkb' => null];
        } catch (\SlevomatEET\FailedRequestException $e) {
            return ['fik' => null, 'bkp' => null, 'pkb' => $e->getRequest()->getPkpCode()];
        } catch (\SlevomatEET\InvalidResponseReceivedException $e) {
            return ['fik' => null, 'bkp' => null, 'pkb' => $e->getResponse()->getRequest()->getPkpCode()];
        }
```

Nevíte v čem může být problém? Je chyba na jejích straně? Díky

**Comment by janlanger** [comment]
Žádný problém s odesláním účtenek nemáme a z kódu nic nevyčtu. Jakou konkrétní chybu dostáváte? chtělo by to dump odchycené exception, z toho by se mělo dát už něco poznat. Web EET měl nějaké potíže, ale to je se samotným účtenkovým API asi nezávislé - viz https://www.hlidaceet.cz/.

Jinak ten kód je jmenuje PKP, ne PKB :-) a jde o binární data, do textové podoby na účtence se má převádět přes `base64_encode`. Na účtence má být také BKP (i když nedostanete FIK) což vypadá že váš kód nevrací.

**Comment by kironet** [comment]
@janlanger 
Upravil jsem to, vrací to BKP, a PKP jsem nechal vratit takto : base64_encode($e->getResponse()->getRequest()->getPkpCode()). Na faktuře vypadá takto: 

> BKP: BDC10AB7-***-77DBA60E- ***-568FC823
> PKP: g+3NpBSkF6D7nqbuRTEEw+az0Y7TjaAv36NFAau TNkLetji8MVrxk/46FsL2e3lBiMUv9GDUitoAD5cU
> OZcPMSixCKSt0GFh8fyfoOAlVKYEahOc7FzBHRW
> +oe+sD+HTGYajk9uYU2I1MZGFzj/A/ZxV4Bx7v73
> C+lLxDo93Bvrjwehjrwejhrghjg43543hJKJKkAJRyCaFpBWH4kS
> Q8ofELoVjPj3HidXg+XXJ9HDfprQK0qu9n1VbnW5
> 0IR1INnRDdNc9le3S/TCuAaKLTTLbc46mh189Zut oS8IK/I17mtPDNLLILq7mL4eyg==

Mohu to nechat takhle na faktuře, protože všechny ostatní se generují správně, ale jenom tahle nechce vratit FIK

btw. když se snažím udělat dump odchycené exception, dostanu 502. 

Díky

**Comment by janlanger** [comment]
@kironet pokud eet nechce vrátit fik pro jednu fakturu a pro ostatní jo, tak tam bude nějaký jiný problém. Zkontroloval bych obsah těch exception, hádám že dostáváte InvalidResponseReceivedException av ní bude nějaké chybové hlášení od FS.
