### ISSUE TITLE
EET Chybove stavy

### ISSUE THREAD

**Issue by theedov** [slevomat/eet-client#33]
Dobrý den,

jak prosím získam chybový stav zaslaný z EET serveru? 
Problém je v tom, že mi script skončí na `InvalidResponseReceivedException` s message `Invalid response received. Check response data for errors and warnings.`

Chtěl bych tedy zjístit v čem je problém, že mi to nevráci FIK.

Edit: Zkoušel jsem `$e->getCode()` vráci to `0`, nicméně nic jsem o 0 nenašel.

**Comment by bogdandovgopol** [comment]
Omlouvám se, nakonec jsem se dostal do rawData a tam je kód 4, vypada to, že mam špatně nastavený datum a čas na serveru.

**Comment by bogdandovgopol** [comment]
Dostal jsem se k rawData a chyba je 4. 
Našel jsem, že chyba 4 je : `použili jste platný certifikát i heslo, ale certifikát nebyl vydán pro použití v EET`

Je možné, že je to kvůli PLAYGROUND módu?
