### ISSUE TITLE
[Otázka] Prodej použitého zboží, 0 DPH správný formát

### ISSUE THREAD

**Issue by kironet** [slevomat/eet-client#35]
Dobrý den,

**prodáváme použité zboží**(já se starám jen o technickou stránku) a **stali jsme se platce dph**. Kontaktovál nas finanční úřad abychom upravili pokladní systém a odesílali platby v jiném formátu. Příklad:

```
Př. Celková částka tržby : 140,-Kč
Celkový základ daně se základní sazbou DPH: 20,08 Kč
Celková DPH se základní sazbou: 4,22 Kč
Celková částka v režimu DPH pro prodej použitého zboží se  základní sazbou: 115,70 Kč.
```

Účetní pořád tvrdí, že na to žádný vzoreček není, že se to ma naťukat ikdyž ji pořad vysvětlujeme, že nenáme fyzickou pokladnu a potřebujeme vzorec... 
Email na finanční úřad se skoro po týdnu vratil jako nedoručený ...

Můžete poradit nebo mě nasměrovat jak se pani dostala k částkam 

**zakl_dan1 = 20,08 
dan1 = 4,22**

Děkují

**Comment by integer** [comment]
@kironet Tohle není asi úplně nejlepší místo, kde se ptát, ale chápu, že to berete jako poslední možnost. Ale je toho dost k nalezení různě po internetu.

Účetní asi nezná Zákon č. 235/2004 Sb. (Zákon o dani z přidané hodnoty), kde jsou popsané postupy, jak se má výpočet provádět. Zjednodušený výtah s příklady najdete třeba tady https://www.stormware.cz/prirucka-uctujeme-online/Zpracovani_DPH/Zpusoby_vypoctu_DPH/

**Comment by Dlahacz** [comment]
> $90 (3) Při použití zvláštního režimu je základem daně přirážka snížená o daň z přirážky. Tato přirážka se stanoví jako rozdíl mezi prodejní cenou obchodníka a pořizovací cenou tohoto zboží. Pokud je tento rozdíl záporný, základem daně je nula. Pro účely tohoto ustanovení se rozumí
> 
> a) prodejní cenou úplata, která byla nebo má být získaná obchodníkem od osoby, které je zboží dodáno, nebo od třetí strany, včetně dotace k ceně, daní, cel, poplatků a vedlejších výdajů jako provize, náklady na balné, přepravu a pojištění požadované obchodníkem od osoby, které je zboží dodáno, s výjimkou částek uvedených v § 36 odst. 5 a 11,
> 
> b) pořizovací cenou úplata stanovená v písmenu a), která byla nebo má být získaná od obchodníka osobou, která mu zboží dodává.

**Comment by Dlahacz** [comment]
Kazdopadne u zvlastniho rezimu se do eet posila pouze celkova cena pro danou sazbu a neni potreba nic vypocitavat. Nebo se pletu? Navic je mozne, ze uctujete pouzite zbozi po zpusobu B (nebo tak nejak se to jmenuje)  a v takovem pripade do konce mesice ani nevite pořizovací cenu, protoze ta je vypoctena az na konci mesice souctem pro jednotlive sazby. Nebo tak nejak, uz je to dlouho co jsem to resil a taky jsem se  u toho pekne navztekal.

**Comment by kironet** [comment]
Diky vsem.

> Kazdopadne u zvlastniho rezimu se do eet posila pouze celkova cena pro danou sazbu a neni potreba nic vypocitavat. Nebo se pletu? Navic je mozne, ze uctujete pouzite zbozi po zpusobu B (nebo tak nejak se to jmenuje) a v takovem pripade do konce mesice ani nevite pořizovací cenu, protoze ta je vypoctena az na konci mesice souctem pro jednotlive sazby. Nebo tak nejak, uz je to dlouho co jsem to resil a taky jsem se u toho pekne navztekal.

Ja uz nevim(vsude se rika neco jineho), tohle poslali z financaku:

> Sdělil jste mi informaci, že podnikáte dle §90 ZDPH s použitým zbožím.
> Je třeba přenastavit pokladní zařízení tak, aby se tržby odesílaly ve správném formátu.
>  
> 
> Př. Celková částka tržby : 140,-Kč
> Celkový základ daně se základní sazbou DPH: 20,08 Kč
> Celková DPH se základní sazbou: 4,22 Kč
> Celková částka v režimu DPH pro prodej použitého zboží se  základní sazbou: 115,70 Kč.
>  
> 
> Takto byste měl mít správně nastavené pokladní zařízení, kdy na účtence bude vidět pouze celková částka tržby 140,-Kč, ale na FS dojde tržba rozdělená ve formátu jak uvádím výše.

Odpovedet jim nejde(emaily se vraci), ucetni nic nevi...

**Comment by Dlahacz** [comment]
No podle me, to co poslala pani urednice, je priklad hlaseni prodani dvou polozek. Jedne pouzite za 115,70 a druhe nepouzite za 24,30. Kdyby se opravdu melo jednat o pouzitou polozku za 140, tak by tech 115,70 prece nebyla celkova caska, ale zaklad.
Pokud by to se to, ale opravdu takhle melo hlasit pro pouzitou polozku za 140 a pokud vite porizovaci cenu, tak nevidim problem to takhle nahlasit. Jesli to ale uctujete po tom zpusobu B, tak by to takhle proste neslo.

**Comment by integer** [comment]
Zprávu od paní úřednice chápu jako:
částka, za kterou jste prodali: 140
částka, za kterou jste nakoupili: 115.70
Rozdíl mezi tím je základ daně - to odpovídá i tomu výše citovanému § 90.
Těch 24.30 je základ + DPH.

Výpočet základu daně provedu jako `24.30/1.21*1.00` => 20.08
DPH spočítám jako `24.30/1.21*0.21` => 4.217 po zaokrouhlení 4.22

Výpočtem to sedí. Jestli to takhle myslel i finančák, to nevim.

**Comment by Dlahacz** [comment]
No sam jsem se v tom ted zamotal, dava to takhle smysl, pokud teda znate porizovaci cenu. Jen bych podotkl, ze dph se nepocita pomoci logickeho vzorecku ala /1.21*0.21, ale koeficientem a u vetsich castek je v tom celkem rozdil.

**Comment by kironet** [comment]
> Zprávu od paní úřednice chápu jako:
> částka, za kterou jste prodali: 140
> částka, za kterou jste nakoupili: 115.70
> Rozdíl mezi tím je základ daně - to odpovídá i tomu výše citovanému § 90.
> Těch 24.30 je základ + DPH.
> 
> Výpočet základu daně provedu jako `24.30/1.21*1.00` => 20.08
> DPH spočítám jako `24.30/1.21*0.21` => 4.217 po zaokrouhlení 4.22
> 
> Výpočtem to sedí. Jestli to takhle myslel i finančák, to nevim.

Tak nakonec je to opravdu tak jak jste to uvedl vy. Jen me ten zajima, jak to odeslat desetinna cisla (20.08, 4.22) kdyz tato knihovna bere jen INT a ne float/double

**Comment by integer** [comment]
@kironet Psal, že odpověď https://github.com/slevomat/eet-client/issues/35#issuecomment-477214227 je tak, jak to finančák očekává. Po čase zprávu smazal, ale přesto myslím, že je možné issue zavřit.

**Comment by kironet** [comment]
Ops, uplně jsem zapoměl, že jsem zprávu úplně smazal, měl jsem v plánu ji opravit. Je to tak, nakonec to opravdu myslela jak to napsal integer. A docela se divila když jsem ji ukázal, že zpravy se vraceli.
