### ISSUE TITLE
Invalid response received. Check response data for errors and warnings.

### ISSUE THREAD

**Issue by adioverride** [slevomat/eet-client#37]
Zdravím, narazil jsem prakticky na stejnou chybu, která se tady již řešila a úplně si s ní nevím rady. Při odeslání se mi vrátí vyjímka: "**Invalid response received. Check response data for errors and warnings.**" a nedaří se mi přijít na to proč.

Kód mám momentálně prakticky stejně jako v ukázce tedy:
`
$key = DIR . "/cert/EET_CA1_Playground_With_Password-CZ683555118.key";
$pub = DIR . "/cert/EET_CA1_Playground-CZ683555118.pub";

$crypto = new CryptographyService($key', $pub', 'eet');

$configuration = new Configuration(
'CZ683555118',
'1',
'1',
EvidenceEnvironment::get(EvidenceEnvironment::PLAYGROUND),
false
);

$client = new Client($crypto, $configuration, new GuzzleSoapClientDriver(new \GuzzleHttp\Client()));

$receipt = new \SlevomatEET\Receipt(
true,
'CZ683555118',
'45',
new \DateTimeImmutable(),
1000
);

try {
$response = $client->send($receipt);
echo $response->getFik();
} catch (\SlevomatEET\FailedRequestException $e) {
echo $e->getRequest()->getPkpCode();
} catch (\SlevomatEET\InvalidResponseReceivedException $e) {
echo $e->getResponse()->getRequest()->getPkpCode();
}
`

Prosím vás, dělám tam nějakou zásadní chybu? Certifikáty jsem stáhnul s celou knihovnou, tak ty asi budou platné.

Díky,
A.

**Comment by janlanger** [comment]
Pokud jste použil certifikáty z repozitáře, tak může být problém způsobený tím. Nebyly dlouho aktualizovány a mezitím vypršela jejich platnost...

Použijte právě vydanou verzi 2 kde jsou čerstvě aktualizované.

Jinak obecně chyby najdete v `$e->getResponse()`...
