### ISSUE TITLE
Inquiry for cooperation

### ISSUE THREAD

**Issue by kposavcevic** [slevomat/eet-client#40]
Hi,

We are working on the implementation of fiscalization for one Czech client and we would need help with connecting to Czech Tax Authorities, so we decided to contact you with the hope that you can help us with your esteemed experience.

At this time, our development team is working on the solution, but we need someone who can help us to connect with Czech Tax Authorities by providing specific local inputs. This would take approximately 3-4 hours of your time per week, depending on the phase of integration. Of course, you would be paid for your time invested.

Please let us know if you are interested in cooperation so we can agree on terms.

Thank you and best regards, 
Kristian

**Comment by janlanger** [comment]
Hi @kposavcevic, you can get in touch with me at mail@janlanger.cz with details.
