### ISSUE TITLE
Kód PKP

### ISSUE THREAD

**Issue by Lokomotom** [slevomat/eet-client#45]
V dokumentu [https://www.etrzby.cz/assets/cs/prilohy/EET_popis_rozhrani_v3.1.1.pdf](https://www.etrzby.cz/assets/cs/prilohy/EET_popis_rozhrani_v3.1.1.pdf) na straně 22 je napsané, že pkp se odesílá až převedené do b64, ale knihovna ho odesílá už v binární podobě. Dochází tam někde k tomu převodu nebo jak je toto vyřešené? Předem díky za pomoc.

**Comment by janlanger** [comment]
Jestli si to pamatuju dobře, tak převod provede PHP Soap klient interně, protože to pole je definované jako base 64 binary data

**Comment by Lokomotom** [comment]
Dobře díky a jak je to tedy s opakovaným zasláním platby protože na této adrese [https://www.etrzby.cz/cs/nejcastejsi-dotazy-vyvojaru](https://www.etrzby.cz/cs/nejcastejsi-dotazy-vyvojaru) jsem našel toto
![Screenshot_2020-08-31 etržby - elektronická evidence tržeb](https://user-images.githubusercontent.com/39953681/91719538-ca01ee00-eb95-11ea-8bb9-9b851786cab5.png)
Takže když se při prvním odeslání dostanu do FailedRequestException nebo InvalidResponseReceivedException, tak tu platbu musím znovu odeslat, ale z té fotky vyplývá, že by měla mít stejné údaje i včetně PKP a BKP, máte toto nějak vyřešené nebo ne, protože PKP a BKP se nedá změnit?

**Comment by janlanger** [comment]
Ano, ani jeden z těchto údajů není součást výpočtu PKP a BKP
